name: C# CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore udp_unicast.sln /p:EnableWindowsTargeting=true

    - name: Build
      run: dotnet build udp_unicast.sln --no-restore --configuration Release /p:EnableWindowsTargeting=true

    - name: Run tests
      run: dotnet test udp_unicast.sln --no-build --verbosity normal /p:EnableWindowsTargeting=true

    - name: Run static analysis
      run: |
        dotnet tool install --global dotnet-format
        dotnet format udp_unicast.sln --check
        # StyleCop.Analyzers 또는 SonarQube 추가 가능
